version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "horror"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xye7ugmbajps"
s3_prefix = "horror"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
